### PR TITLE
CCD-2344: Flux changes

### PR DESCRIPTION
**Pull request by paulridout**
### JIRA link (if applicable) ###
CCD-2344 (https://tools.hmcts.net/jira/browse/CCD-2344)

### Change description ###
Changed ccd-api-gateway-web demo.yaml.  Moved image to nodejs section and removed empty java section.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by skandala-cgi — DISMISSED** [review]
LGTM

**Review by paulridout — COMMENTED** [review]
Changes to the ccd-case-print-service demo.yaml file look OK to me

**Review by kaanaktas — APPROVED** [review]
lgtm

**Review by skandala-cgi — APPROVED** [review]
LGTM

**Review by MSancaktutar — APPROVED** [review]

**Review by hemantt — APPROVED** [review]

**Review by cakeben — APPROVED** [review]

**Pull request merged**
