### PR TITLE
DTSPO-4182 CCD Demo Flux v2 Image Automation

### PR DESCRIPTION
**Pull request by chrisorisawayi**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-4182

### Change description ###
Added Flux v2 image automation for CCD demo.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Review by nathan-clark — COMMENTED** [review]
I think the ac-int yaml was temporary only @smathangi maybe able to comment further on whether this is still required.

**Comment by smathangi** [comment]
> I think the ac-int yaml was temporary only @smathangi maybe able to comment further on whether this is still required.

Yes it's required for next two months (though it's temporary)

**Comment by chrisorisawayi** [comment]
> I think the ac-int yaml was temporary only @smathangi maybe able to comment further on whether this is still required.

as requested, ac-int yaml changes now reverted and will not be included in flux v2

**Comment by chrisorisawayi** [comment]
Superseded by #11771

**Pull request closed without merging**
