### PR TITLE
DTSPO-2296 - Payment Sendgrid migration

### PR DESCRIPTION
**Pull request by endakelly**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-2296

### Change description ###
Adding key vault and environment variables for migrating Payment AAT to SendGrid

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
Secrets should be using the values from the helm chart (no .'s are allowed in secrets)

https://github.com/hmcts/ccpay-payment-app/blob/master/charts/payment-api/values.yaml#L83-L123

**Comment by endakelly** [comment]
> Secrets should be using the values from the helm chart (no .'s are allowed in secrets)
> 
> https://github.com/hmcts/ccpay-payment-app/blob/master/charts/payment-api/values.yaml#L83-L123

Fixed as suggested by Tim

**Review by timja — CHANGES_REQUESTED** [review]
the actual password seems to be missing?

`- spring-mail-password` unless I'm missing something?

**Comment by endakelly** [comment]
> the actual password seems to be missing?
> 
> `- spring-mail-password` unless I'm missing something?

Yeah I missed that one. Added in there now

**Review by timja — APPROVED** [review]

**Pull request merged**
