### PR TITLE
upgrade artifactory chart version to latest

### PR DESCRIPTION
**Pull request by NickAzureDevops**
### Jira link

See [DTSPO-22631](https://tools.hmcts.net/jira/browse/DTSPO-22631)

## Description

updated artifactory to latest chart version on ptl from  107.90.9 to 107.98.9

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested on sbox ptl and working https://github.com/hmcts/cnp-flux-config/pull/35678 

### Issues Found

Please list any issues found during testing and how they were resolved:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Deployment Steps

None

## Additional Information

Please add any other information that is important to this PR, such as screenshots, logs, or links to other related PRs.

## 🤖AEP PR SUMMARY🤖

_I'm a bot that generates AI summaries of pull requests, see [AEP](https://kainossoftwareltd.github.io/ai-enhanced-platform/) for more details_

- Deleted file: `apps/artifactory/artifactory/artifactory-sbox.yaml`
- Updated `apps/artifactory/artifactory/artifactory.yaml`: changed version from 107.90.9 to 107.98.9
- Updated `apps/artifactory/sbox-intsvc/base/kustomization.yaml`: removed a path to a file and its contents.

### CODE REVIEW

**Review by reespozzi — COMMENTED** [review]
Please can you disable this in jenkins first and get that PR through

**Comment by NickAzureDevops** [comment]
> Please can you disable this in jenkins first and get that PR through

same PR here https://github.com/hmcts/cnp-jenkins-library/pull/1288

**Comment by NickAzureDevops** [comment]
> > Please can you disable this in jenkins first and get that PR through
> 
> same PR here [hmcts/cnp-jenkins-library#1288](https://github.com/hmcts/cnp-jenkins-library/pull/1288) @reespozzi

Other PR have been merged

**Review by reespozzi — APPROVED** [review]
Jenkins is bypassing artifactory whilst this goes through https://github.com/hmcts/cnp-jenkins-library/pull/1288

**Pull request merged**
