### PR TITLE
pinned adoption web and cos-api prod images

### PR DESCRIPTION
**Pull request by abidfs**
### Change description ###
pinned adoption web and cos-api prod images

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by thomast1906 — CHANGES_REQUESTED** [review]
Is this image needed? its in the base of adoption-cos-api.yaml

**Review by gauravtomar-gh — DISMISSED** [review]

**Comment by abidfs** [comment]
> Is this image needed? its in the base of adoption-cos-api.yaml

@thomast1906 this is required to pin the image and stop further image automation in prod
Hope that answers your question

**Review by gauravtomar-gh — APPROVED** [review]

**Comment by gauravtomar-gh** [comment]
> Is this image needed? its in the base of adoption-cos-api.yaml

@thomast1906 , Kindly review the change requested. We are targeting to close this.

**Review by timja — CHANGES_REQUESTED** [review]
Pinning image is not allowed, Git must be in sync.

Why are you doing this?

**Review by thomast1906 — CHANGES_REQUESTED** [review]
Have discussed with Sayyad, this is not recommended/allowed to pin to a specific image in Production

**Pull request closed without merging**
