### PR TITLE
camunda temp patch to fix ad auth

### PR DESCRIPTION
**Pull request by thomast1906**
### Change description ###
camunda temp patch to fix ad auth

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by reespozzi — APPROVED** [review]

**Review by timja — COMMENTED** [review]
have you tested this?

**Review by cakeben — APPROVED** [review]

**Comment by thomast1906** [comment]
will apply directly to app config https://github.com/hmcts/camunda-bpm

**Comment by thomast1906** [comment]
Added to here: https://github.com/hmcts/camunda-bpm/commit/9a882dcbefeb5634017ac77cc952b5f594c4e13f 

Closing this PR for now

**Comment by thomast1906** [comment]
Added to here: https://github.com/hmcts/camunda-bpm/commit/9a882dcbefeb5634017ac77cc952b5f594c4e13f 

Closing this PR for now

**Pull request closed without merging**
