### PR TITLE
Readjust cpu and memory as per avg usage on prod

### PR DESCRIPTION
**Pull request by adusumillipraveen**
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
all looks reasonable

**Review by jmcadam — CHANGES_REQUESTED** [review]
Looks good, but we're missing:

- doc-assembley-prod
- rpe-send-letter-service-perftest

**Review by rajaram-nagarajan — DISMISSED** [review]
LGTM

**Comment by adusumillipraveen** [comment]
> 

fixed, send letter perftest. dg-doc-assembly should be fine as i have changed default (for all clusters)

**Review by jmcadam — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Pull request merged**
