### PR TITLE
Update Image that do not exist 

### PR DESCRIPTION
**Pull request by NickAzureDevops**
### Jira link

See [DTSPO-18669](https://tools.hmcts.net/jira/browse/DTSPO-18669)

### Change description

Update image for demo that do not exist 

also two pod failing on it

tax-tribunals                 tax-tribunals-application-base-cc6c6fb9-k45m9              ImagePullBackOff    
tax-tribunals                 tax-tribunals-application-base-cc6c6fb9-klqjj                    ImagePullBackOff  

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

## 🤖AEP PR SUMMARY🤖

_I'm a bot that generates AI summaries of pull requests, see [AEP](https://kainossoftwareltd.github.io/ai-enhanced-platform/) for more details_

### apps/tax-tribunals/tax-tribunals-application/demo.yaml
- Changed the `image` from `hmctspublic.azurecr.io/tax-tribunals/application:pr-274-b50406f-20240815132426` to the same value.

### CODE REVIEW

**Comment by NickAzureDevops** [comment]
metrics server running and saw it is on 

`tax-tribunals-application-sidekiq-6fb584457d-fg8vm   2m           246Mi           `

**Comment by NickAzureDevops** [comment]
maybe not enough cpu resource

**Comment by reespozzi** [comment]
is this what's actually stopping the pod starting? I could see an image pull error before

**Comment by NickAzureDevops** [comment]
> is this what's actually stopping the pod starting? I could see an image pull error before

sorted now. yeh wrong image

**Review by reespozzi — APPROVED** [review]

**Pull request merged**
