### PR TITLE
RDM-10199 Deploy definition-store-api:pr-830-73c8b7c9 to AAT

### PR DESCRIPTION
**Pull request by rafalkalita**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDM-10199

### Change description ###
Deploying definition-store-api:pr-830-73c8b7c9 to AAT to test RDM-10199

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

### CODE REVIEW

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Comment by hemantt** [comment]
@rafalkalita @MSancaktutar I dont think the RPE checks allow AAT deployment of custom PRs

**Comment by rafalkalita** [comment]
Yes, we have noticed @hemantt Not even staging, we were trying to use from the master build.

**Comment by rafalkalita** [comment]
We have realised deploying the PR code to AAT is restricted.

**Pull request closed without merging**
