### PR TITLE
NFDIV Update Case Type

### PR DESCRIPTION
**Pull request by lara-mpt**
### Change description ###
Update the case type for nfdiv 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by ernestman28 — DISMISSED** [review]
LGTM

**Review by ernestman28 — DISMISSED** [review]
LGTM

**Comment by linusnorton** [comment]
sorry @ernestman28 could you re-review?

**Review by ernestman28 — APPROVED** [review]
LGTM

**Pull request closed without merging**
