### PR TITLE
NFDIV-1575 : Added new cron job config for lower environments

### PR DESCRIPTION
**Pull request by sunilnatikar**
### JIRA link ###
https://tools.hmcts.net/jira/browse/NFDIV-1575

### Change description ###
Added new cron config for SystemNotifyJointApplicantCanSwitchToSoleTask

Case API PR: https://github.com/hmcts/nfdiv-case-api/pull/2174

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by nitinprabhu — APPROVED** [review]
Please merge it only after merging the task

**Comment by sunilnatikar** [comment]
> Please merge it only after merging the task

task is merged to master now. 
Awaiting plat-ops review on this one.

**Review by adusumillipraveen — CHANGES_REQUESTED** [review]
All new apps should go to flux v2 config

**Comment by sunilnatikar** [comment]
> All new apps should go to flux v2 config

updated to v2

**Pull request closed without merging**
