### PR TITLE
Service Auth Provider version bump to onboard the Access Management J…

### PR DESCRIPTION
**Pull request by nitishsingla1234**
Access Management Judicial Booking Service.

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/AM-792

### Change description ###
Service Auth Provider version bump to onboard the Access Management Judicial Booking Service.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by nitishsingla1234** [comment]
Can someone from RPE team please have a look.

**Comment by timja** [comment]
I think this has already been covered in https://github.com/hmcts/cnp-flux-config/pull/4057 ?

**Comment by nitishsingla1234** [comment]
Thanks @timja  It seems that there is an automated process to bump the versions :)

**Comment by timja** [comment]
> Thanks @timja It seems that there is an automated process to bump the versions :)

Yes there is, sometimes people like to do it themselves as I think the automatic bumper only runs hourly, so you can race to beat the machine

**Pull request closed without merging**
