### PR TITLE
Force case-loader to deploy old image and exclude from tests

### PR DESCRIPTION
**Pull request by damien-cooke**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by thomast1906** [comment]
@damien-cooke what is the need for this? can it not be tested in aat/lower env?

**Comment by damien-cooke** [comment]
@thomast1906 we need to get it back working again so we do not impact prod further. The only env case loader works in is aat and we have tried multiple fixes but nothing that is working. We need to deploy the old image to prod to get it working again while we work on a fix going forward. I am hoping doing it this way will allow us to still be able to deploy potential fixes to aat.

**Comment by adusumillipraveen** [comment]
> @thomast1906 we need to get it back working again so we do not impact prod further. The only env case loader works in is aat and we have tried multiple fixes but nothing that is working. We need to deploy the old image to prod to get it working again while we work on a fix going forward. I am hoping doing it this way will allow us to still be able to deploy potential fixes to aat.

You should rather revert your code to working condition than forcing images. master should reflect what's on prod.

**Comment by damien-cooke** [comment]
@adusumillipraveen the code changes are Java 17 upgrade which is now enforced in the pipeline.

**Comment by adusumillipraveen** [comment]
> @adusumillipraveen the code changes are Java 17 upgrade which is now enforced in the pipeline.

Unfortunate that we couldn't upgrade in time.  I will let Thomas give it a tick.

**Review by timja — APPROVED** [review]

**Review by ss-evoco — APPROVED** [review]

**Pull request merged**
