### PR TITLE
added adoption jurisdiction in xui webapp

### PR DESCRIPTION
**Pull request by abidfs**
### Change description ###
added adoption jurisdiction in xui webapp

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by Mo-Lala84 — COMMENTED** [review]
There are conflicts which needs fixing.

**Review by Mo-Lala84 — CHANGES_REQUESTED** [review]
please resolve conflicts

**Comment by gauravtomar-gh** [comment]
Conflict resolved. Please approve and merge.

**Pull request closed without merging**
