### PR TITLE
DTSCCI-17 enabling the polling scheduler in aat for tests with the mu…

### PR DESCRIPTION
**Pull request by gmikerlemos**
…ltiple camunda instances.

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/DTSCCI-17
### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

### CODE REVIEW

**Review by nigeldunne — APPROVED** [review]

**Comment by jthmcts** [comment]
why?

**Review by jthmcts — CHANGES_REQUESTED** [review]
What is this for?

**Review by linusnorton — DISMISSED** [review]

**Review by rishikrsharma — DISMISSED** [review]

**Comment by gmikerlemos** [comment]
> What is this for?

wrong file. it is meant to be civil.

**Comment by rishikrsharma** [comment]
> What is this for?

@jthmcts  its for civil

**Comment by gmikerlemos** [comment]
> What is this for?

can you remove this block please?

**Pull request closed without merging**
