### PR TITLE
Update fpl-case-service aat + perftest computational resources

### PR DESCRIPTION
**Pull request by luigibk**
### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by timja** [comment]
related https://github.com/hmcts/cnp-flux-config/pull/565

**Comment by geek-soft** [comment]
Closing, https://github.com/hmcts/cnp-flux-config/pull/565 supersedes it as I want to use newer helm version.

**Comment by luigibk** [comment]
This does not have anything to do with the new java helm chart. It is still needed even using the latest chart-java

**Comment by geek-soft** [comment]
I meant using newer version of FPL service chart.

**Pull request merged**
