### PR TITLE
Prod cnp-flux changes

### PR DESCRIPTION
**Pull request by shashisk97**
Hi Team,

**https://github.com/hmcts/cnp-flux-config/tree/prl-service-prod/k8s/prod/common** we dont have **private-law** directory , are we missing something? as we followed the below link and did not perform V2 steps:
https://github.com/hmcts/cnp-flux-config/blob/master/docs/app-deployment.md 

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-963

### Change description ###
Prod cnp-flux changes for private-law service

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by shreedhar-hmcts — CHANGES_REQUESTED** [review]
Please remove k8s/namespaces/rd/rd-professional-api/prod.yaml file changes

**Review by AlokDatta — APPROVED** [review]

**Review by reespozzi — APPROVED** [review]
Looking to get second pair of eyes too but looks OK to me so far

**Review by reespozzi — CHANGES_REQUESTED** [review]
Holding off until second review

**Review by reespozzi — APPROVED** [review]

**Comment by AlokDatta** [comment]
> Please remove k8s/namespaces/rd/rd-professional-api/prod.yaml file changes
Addressed and removed.

**Pull request merged**
