### PR TITLE
Rdm 11820 prod

### PR DESCRIPTION
**Pull request by sumansreenivasan**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CCD-774
### Change description ###
whitelist em_hrs_api in ccd-data-store-api on Prod
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by MSancaktutar — APPROVED** [review]
Lgtm, assuming merge after lower envs pr.

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Review by MSancaktutar — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Review by benouaer — APPROVED** [review]

**Review by MSancaktutar — APPROVED** [review]
lgtm

**Pull request merged**
