### PR TITLE
delete cmc pay from demo

### PR DESCRIPTION
**Pull request by NickAzureDevops**
### Jira link

See [DTSPO-18669](https://tools.hmcts.net/jira/browse/DTSPO-18669)

### Change description

delete cmc pay money claims from demo as no longer needed which has been requested from the team

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

## 🤖AEP PR SUMMARY🤖

_I'm a bot that generates AI summaries of pull requests, see [AEP](https://kainossoftwareltd.github.io/ai-enhanced-platform/) for more details_

### apps/money-claims/demo/base/kustomization.yaml
- Removed the reference to `cmc-pay/cmc-pay.yaml` resource.
- Removed the reference to `cmc-pay/demo.yaml` patch file.

### CODE REVIEW

**Review by thomast1906 — CHANGES_REQUESTED** [review]
This is deleting, rather than commenting out?

**Comment by NickAzureDevops** [comment]
> This is deleting, rather than commenting out?

Yes team said it is not needed as got told to nuke it @thomast1906

**Review by reespozzi — APPROVED** [review]
Apparently no longer used / decommed

**Comment by thomast1906** [comment]
Thanks, please ensure comment / summaries are correct. 
- This was removing from a file, rather than commenting out for example

**Pull request closed without merging**
