### PR TITLE
Update ccd-case-management-web-redirect.yaml

### PR DESCRIPTION
**Pull request by MSancaktutar**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CCD-2336

### Change description ###
correction attempt for ccd-case-management-web-redirect

**Does this PR introduce a breaking change?** (check one with "x")

```
[Y] Yes
[ ] No
```

### CODE REVIEW

**Review by jrichards-hmcts — APPROVED** [review]
Approved.

**Review by rajaram-nagarajan — APPROVED** [review]
LGTM

**Review by thomast1906 — COMMENTED** [review]
as discussed when I approved the Production PR
https://github.com/hmcts/cnp-flux-config/blob/master/k8s/perftest/common/ccd/ccd-case-management-web-redirect.yaml#L9
You had made a slight difference to the above in perftest^
https://github.com/hmcts/cnp-flux-config/blob/master/k8s/prod/common/ccd/ccd-case-management-web-redirect.yaml#L9

**Comment by MSancaktutar** [comment]
> as discussed when I approved the Production PR https://github.com/hmcts/cnp-flux-config/blob/master/k8s/perftest/common/ccd/ccd-case-management-web-redirect.yaml#L9 You had made a slight difference to the above in perftest^ https://github.com/hmcts/cnp-flux-config/blob/master/k8s/prod/common/ccd/ccd-case-management-web-redirect.yaml#L9

Hi @thomast1906  - That's is knowingly so as I wanted to redirect https://www.ccd.... as well as http://ccd....

**Review by timja — APPROVED** [review]

**Pull request merged**
