### PR TITLE
Add doc and script for adding MI access from another project

### PR DESCRIPTION
**Pull request by chris-pateman**
### Change description ###
Adding documentation and script on how to give your project access to another projects resources via their Managed Identity

A few developers have questions how to configure this on flux and I find this the best place.
the example is/was the civil teams civil-service is connecting to the aac vault aac-aat. For their pod to have access it needs to use the Managed Identity aac-aat-mi. 
This documentation will enable developers/engineers to config on their own without assistance.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
could you explain the need a bit more? the description in the PR is about the what and not the why

**Comment by chris-pateman** [comment]
> could you explain the need a bit more? the description in the PR is about the what and not the why

Updated. is this ok?

**Comment by timja** [comment]
Could you be more explicit on teams / what or why they are doing this for?

**Comment by chris-pateman** [comment]
> Could you be more explicit on teams / what or why they are doing this for?

updated and added

**Comment by timja** [comment]
What secret / why?

generally teams aren't supposed to access other vaults at runtime, we want runtime apps to be quite limited. but are they deploying another pod in their namespace for some reason?

**Pull request closed without merging**
